language: c

compiler: gcc

before_install:
  - sudo apt-get install libbluetooth-dev libgtk-3-dev libwebkit2gtk-4.0-dev
  
install:
  - make configure

script:
  - make all extras
  - make release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist-*/luajls-*.*
  skip_cleanup: true
  draft: true
