language: c

compiler: gcc

before_install:
  - sudo apt-get install libbluetooth-dev
  
install:
  - make configure

script:
  - make all
  - make dist-jls test luajls-archive

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist-*/luajls-*.*
  skip_cleanup: true
  draft: true
